import { StyleSheet } from "react-native";
import { radius, space, type } from "../clientTheme";

export const makeStyles = (t) =>
  StyleSheet.create({
    screen: { flex: 1, backgroundColor: t.bg },
    safeArea: { flex: 1 },
    content: { paddingHorizontal: 20, paddingBottom: 40 },

    backBtn: {
      width: 40,
      height: 40,
      borderRadius: 20,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: t.card,
      borderWidth: 1,
      borderColor: t.borderSoft,
      marginTop: space.xs,
      marginBottom: space.md,
    },
    title: {
      ...type.title,
      fontFamily: "Outfit_700Bold",
      color: t.textPrimary,
    },
    subtitle: {
      ...type.callout,
      fontFamily: "Inter_400Regular",
      color: t.textSecondary,
      marginTop: 4,
      marginBottom: space.lg,
    },
    sectionLabel: {
      ...type.overline,
      fontFamily: "Inter_600SemiBold",
      color: t.textTertiary,
      textTransform: "uppercase",
      marginTop: space.lg,
      marginBottom: space.sm,
    },

    primaryBtn: {
      height: 54,
      borderRadius: 18,
      flexDirection: "row",
      gap: 10,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: t.accent,
      ...t.accentShadow,
    },
    primaryBtnDisabled: { opacity: 0.45 },
    primaryBtnText: {
      fontSize: 16,
      fontFamily: "Inter_600SemiBold",
      color: t.onAccent,
    },
    dangerBtn: {
      height: 48,
      borderRadius: 16,
      alignItems: "center",
      justifyContent: "center",
      marginTop: space.sm,
    },
    dangerBtnText: {
      fontSize: 15,
      fontFamily: "Inter_600SemiBold",
      color: t.danger,
    },

    card: {
      backgroundColor: t.card,
      borderRadius: radius.card,
      borderWidth: 1,
      borderColor: t.borderSoft,
      padding: space.md,
      ...t.cardShadow,
    },
    cardDate: {
      fontSize: 15,
      fontFamily: "PlusJakartaSans_600SemiBold",
      color: t.textPrimary,
      marginBottom: space.sm,
    },
    tileGrid: { flexDirection: "row", flexWrap: "wrap", gap: 10 },
    tile: {
      minWidth: 92,
      flexGrow: 1,
      backgroundColor: t.accentSoft,
      borderRadius: 14,
      paddingVertical: 12,
      paddingHorizontal: 14,
    },
    tileLabel: {
      fontSize: 12,
      fontFamily: "Inter_500Medium",
      color: t.textSecondary,
      marginBottom: 4,
    },
    tileValue: {
      fontSize: 20,
      fontFamily: "Outfit_700Bold",
      color: t.accent,
    },
    tileUnit: {
      fontSize: 12,
      fontFamily: "Inter_500Medium",
      color: t.textSecondary,
    },

    historyRow: {
      backgroundColor: t.card,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: t.borderSoft,
      padding: 14,
      marginBottom: 10,
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
    },
    historyBody: { flex: 1 },
    historyDate: {
      fontSize: 14,
      fontFamily: "Inter_600SemiBold",
      color: t.textPrimary,
      marginBottom: 6,
    },
    chips: { flexDirection: "row", flexWrap: "wrap", gap: 6 },
    chip: {
      backgroundColor: t.cardElevated,
      borderRadius: 8,
      paddingVertical: 4,
      paddingHorizontal: 8,
    },
    chipText: {
      fontSize: 12,
      fontFamily: "Inter_500Medium",
      color: t.textSecondary,
    },
    photoCount: {
      flexDirection: "row",
      alignItems: "center",
      gap: 4,
    },
    photoCountText: {
      fontSize: 12,
      fontFamily: "Inter_600SemiBold",
      color: t.accent,
    },

    emptyCard: {
      backgroundColor: t.card,
      borderRadius: radius.card,
      borderWidth: 1,
      borderColor: t.borderSoft,
      padding: 28,
      alignItems: "center",
      marginTop: space.lg,
    },
    emptyTitle: {
      fontSize: 16,
      fontFamily: "PlusJakartaSans_600SemiBold",
      color: t.textPrimary,
      marginTop: space.sm,
    },
    emptyText: {
      fontSize: 13,
      fontFamily: "Inter_400Regular",
      color: t.textSecondary,
      textAlign: "center",
      marginTop: 6,
      lineHeight: 19,
    },

    // Check-in form
    dateRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      backgroundColor: t.card,
      borderRadius: 16,
      borderWidth: 1,
      borderColor: t.borderSoft,
      padding: 6,
    },
    dateArrow: {
      width: 42,
      height: 42,
      borderRadius: 12,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: t.accentSoft,
    },
    dateArrowDisabled: { opacity: 0.35 },
    dateText: {
      flex: 1,
      textAlign: "center",
      fontSize: 15,
      fontFamily: "Inter_600SemiBold",
      color: t.textPrimary,
    },
    fieldGrid: { flexDirection: "row", flexWrap: "wrap", gap: 12 },
    fieldGroup: { width: "47%", flexGrow: 1 },
    fieldLabel: {
      fontSize: 13,
      fontFamily: "Inter_600SemiBold",
      color: t.textSecondary,
      marginBottom: 6,
    },
    fieldUnit: { fontFamily: "Inter_400Regular", color: t.textTertiary },
    fieldInput: {
      backgroundColor: t.inputBg,
      borderWidth: 1,
      borderColor: t.border,
      borderRadius: 14,
      height: 50,
      paddingHorizontal: 14,
      fontSize: 18,
      fontFamily: "Inter_600SemiBold",
      color: t.textPrimary,
      textAlign: "center",
    },

    guidance: {
      ...type.callout,
      fontFamily: "Inter_400Regular",
      color: t.textSecondary,
      marginBottom: space.sm,
    },
    photoGrid: { flexDirection: "row", flexWrap: "wrap", gap: 12 },
    slot: { width: "47%", flexGrow: 1 },
    slotFrame: {
      aspectRatio: 3 / 4,
      borderRadius: 18,
      overflow: "hidden",
      backgroundColor: t.card,
      borderWidth: 1,
      borderColor: t.border,
      borderStyle: "dashed",
      alignItems: "center",
      justifyContent: "center",
      padding: 12,
    },
    slotFrameFilled: { borderStyle: "solid", padding: 0 },
    slotImage: { width: "100%", height: "100%" },
    slotLabel: {
      fontSize: 14,
      fontFamily: "PlusJakartaSans_600SemiBold",
      color: t.textPrimary,
      marginTop: 8,
    },
    slotHint: {
      fontSize: 11,
      lineHeight: 15,
      fontFamily: "Inter_400Regular",
      color: t.textTertiary,
      textAlign: "center",
      marginTop: 4,
    },
    slotCaption: {
      fontSize: 13,
      fontFamily: "Inter_600SemiBold",
      color: t.textPrimary,
      marginTop: 6,
    },
    slotRemove: {
      position: "absolute",
      top: 8,
      right: 8,
      width: 30,
      height: 30,
      borderRadius: 15,
      alignItems: "center",
      justifyContent: "center",
      backgroundColor: "rgba(0,0,0,0.5)",
    },

    formNote: {
      fontSize: 13,
      fontFamily: "Inter_500Medium",
      color: t.danger,
      textAlign: "center",
      marginTop: space.sm,
    },
    privacyNote: {
      fontSize: 12,
      fontFamily: "Inter_400Regular",
      color: t.textTertiary,
      textAlign: "center",
      marginTop: space.md,
      lineHeight: 17,
    },
  });
