import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: "#FFFFFF" },
  scroll: { flex: 1 },
  scrollContent: { paddingHorizontal: 20, paddingBottom: 48 },

  header: { marginBottom: 20 },
  backText: {
    fontSize: 14,
    fontFamily: "Inter_500Medium",
    color: "#7C3AED",
    marginBottom: 14,
  },
  title: {
    fontSize: 22,
    fontFamily: "Outfit_700Bold",
    color: "#111827",
    marginBottom: 2,
  },
  subtitle: {
    fontSize: 14,
    fontFamily: "Inter_400Regular",
    color: "#6B7280",
  },

  // ── Week selector ──
  weekSelector: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#F9FAFB",
    borderRadius: 14,
    padding: 4,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: "#F3F4F6",
  },
  weekArrow: {
    width: 42,
    height: 42,
    alignItems: "center",
    justifyContent: "center",
  },
  weekArrowText: {
    fontSize: 24,
    color: "#7C3AED",
    lineHeight: 28,
  },
  weekLabel: {
    flex: 1,
    textAlign: "center",
    fontSize: 15,
    fontFamily: "Inter_600SemiBold",
    color: "#111827",
  },

  // ── Section label ──
  sectionLabel: {
    fontSize: 11,
    fontFamily: "Inter_600SemiBold",
    color: "#9CA3AF",
    letterSpacing: 1.2,
    marginBottom: 10,
  },

  // ── Sessions per week ──
  sessionsRow: {
    flexDirection: "row",
    gap: 10,
    marginBottom: 20,
  },
  sessionChip: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: "center",
    backgroundColor: "#F9FAFB",
    borderWidth: 1,
    borderColor: "#E5E7EB",
  },
  sessionChipActive: {
    backgroundColor: "rgba(124,58,237,0.1)",
    borderColor: "#7C3AED",
  },
  sessionChipText: {
    fontSize: 18,
    fontFamily: "PlusJakartaSans_700Bold",
    color: "#9CA3AF",
  },
  sessionChipTextActive: { color: "#7C3AED" },

  // ── Training tabs ──
  tabRow: { gap: 8, marginBottom: 16 },
  tab: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 10,
    paddingHorizontal: 18,
    borderRadius: 12,
    backgroundColor: "#F9FAFB",
    borderWidth: 1,
    borderColor: "#E5E7EB",
    gap: 6,
  },
  tabActive: { backgroundColor: "#7C3AED", borderColor: "#7C3AED" },
  tabText: {
    fontSize: 13,
    fontFamily: "Inter_600SemiBold",
    color: "#6B7280",
  },
  tabTextActive: { color: "#FFFFFF" },
  tabBadge: {
    backgroundColor: "rgba(255,255,255,0.3)",
    borderRadius: 8,
    minWidth: 20,
    height: 20,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 4,
  },
  tabBadgeText: {
    fontSize: 11,
    fontFamily: "Inter_700Bold",
    color: "#FFFFFF",
  },

  // ── Added exercises ──
  emptyExercises: {
    backgroundColor: "#F9FAFB",
    borderRadius: 14,
    padding: 20,
    alignItems: "center",
    marginBottom: 8,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    borderStyle: "dashed",
  },
  emptyExercisesText: {
    fontSize: 14,
    fontFamily: "Inter_400Regular",
    color: "#9CA3AF",
    textAlign: "center",
    lineHeight: 20,
  },
  exerciseList: { gap: 8, marginBottom: 8 },
  exerciseCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderRadius: 14,
    padding: 14,
    borderWidth: 1,
    borderColor: "#E5E7EB",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 6,
    elevation: 1,
    gap: 12,
  },
  exerciseNumBadge: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: "rgba(124,58,237,0.1)",
    alignItems: "center",
    justifyContent: "center",
  },
  exerciseNumText: {
    fontSize: 13,
    fontFamily: "Inter_700Bold",
    color: "#7C3AED",
  },
  exerciseInfo: { flex: 1 },
  exerciseName: {
    fontSize: 14,
    fontFamily: "Inter_600SemiBold",
    color: "#111827",
  },
  exerciseMeta: {
    fontSize: 12,
    fontFamily: "Inter_400Regular",
    color: "#6B7280",
    marginTop: 2,
  },
  removeBtn: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: "rgba(239,68,68,0.08)",
    alignItems: "center",
    justifyContent: "center",
  },
  removeBtnText: {
    fontSize: 12,
    color: "#EF4444",
    fontFamily: "Inter_600SemiBold",
  },

  // ── Category filter ──
  categoryRow: { gap: 8, paddingVertical: 4, marginBottom: 12 },
  categoryChip: {
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 20,
    backgroundColor: "#F9FAFB",
    borderWidth: 1,
    borderColor: "#E5E7EB",
  },
  categoryChipActive: { backgroundColor: "#7C3AED", borderColor: "#7C3AED" },
  categoryChipText: {
    fontSize: 13,
    fontFamily: "Inter_500Medium",
    color: "#374151",
  },
  categoryChipTextActive: { color: "#FFFFFF" },

  // ── Exercise picker ──
  exercisePickerRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 13,
    borderBottomWidth: 1,
    borderBottomColor: "#F3F4F6",
  },
  exercisePickerName: {
    flex: 1,
    fontSize: 14,
    fontFamily: "Inter_500Medium",
    color: "#111827",
  },
  addExerciseBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "rgba(124,58,237,0.1)",
    alignItems: "center",
    justifyContent: "center",
  },
  addExerciseBtnText: {
    fontSize: 20,
    color: "#7C3AED",
    lineHeight: 26,
    fontFamily: "Inter_400Regular",
  },

  saveRow: { marginTop: 28 },

  // ── Delete program ──
  deleteBtn: {
    marginTop: 12,
    height: 52,
    borderRadius: 16,
    borderWidth: 1.5,
    borderColor: "#FECACA",
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 8,
  },
  deleteBtnText: {
    fontSize: 15,
    fontFamily: "Inter_600SemiBold",
    color: "#EF4444",
  },

  // ── Save-preview recap rows (ConfirmSheet) ──
  recapRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  recapTrening: {
    fontSize: 14,
    fontFamily: "Inter_600SemiBold",
    color: "#111827",
  },
  recapCount: {
    fontSize: 14,
    fontFamily: "Inter_600SemiBold",
    color: "#7C3AED",
  },
  recapCountMuted: {
    color: "#B0B4BB",
    fontFamily: "Inter_500Medium",
  },
  recapTotalRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderTopWidth: 1,
    borderTopColor: "#EEF0F2",
    paddingTop: 10,
    marginTop: 2,
  },
  recapTotalLabel: {
    fontSize: 13,
    fontFamily: "Inter_600SemiBold",
    color: "#6B7280",
  },
  recapTotalValue: {
    fontSize: 15,
    fontFamily: "Outfit_700Bold",
    color: "#111827",
  },

  // ── Modal ──
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.45)",
    justifyContent: "center",
    paddingHorizontal: 24,
  },
  modalCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 22,
    padding: 24,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.15,
    shadowRadius: 24,
    elevation: 12,
  },
  modalTitle: {
    fontSize: 18,
    fontFamily: "PlusJakartaSans_700Bold",
    color: "#111827",
    marginBottom: 4,
  },
  modalSubtitle: {
    fontSize: 13,
    fontFamily: "Inter_400Regular",
    color: "#9CA3AF",
    marginBottom: 22,
  },
  modalInputRow: { flexDirection: "row", gap: 14, marginBottom: 14 },
  modalInputGroup: { flex: 1 },
  modalInputLabel: {
    fontSize: 12,
    fontFamily: "Inter_600SemiBold",
    color: "#374151",
    marginBottom: 6,
  },
  modalInput: {
    backgroundColor: "#F9FAFB",
    borderWidth: 1,
    borderColor: "#E5E7EB",
    borderRadius: 10,
    padding: 12,
    fontSize: 18,
    fontFamily: "Inter_600SemiBold",
    color: "#111827",
    textAlign: "center",
  },
  modalNoteInput: {
    backgroundColor: "#F9FAFB",
    borderWidth: 1,
    borderColor: "#E5E7EB",
    borderRadius: 10,
    padding: 12,
    fontSize: 14,
    fontFamily: "Inter_400Regular",
    color: "#111827",
    marginBottom: 22,
  },
  modalBtns: { flexDirection: "row", gap: 10 },
  modalBtn: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: "center",
  },
  modalBtnCancel: {
    backgroundColor: "#F9FAFB",
    borderWidth: 1,
    borderColor: "#E5E7EB",
  },
  modalBtnCancelText: {
    fontSize: 14,
    fontFamily: "Inter_600SemiBold",
    color: "#6B7280",
  },
  modalBtnConfirm: { backgroundColor: "#7C3AED" },
  modalBtnConfirmText: {
    fontSize: 14,
    fontFamily: "Inter_600SemiBold",
    color: "#FFFFFF",
  },
});
