import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#FFFFFF",
  },
  container: {
    flex: 1,
    paddingHorizontal: 20,
  },
  loadingContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  contentContainer: {
    paddingBottom: 24,
  },
  title: {
    fontSize: 22,
    fontFamily: "Outfit_700Bold",
    color: "#111827",
    marginBottom: 4,
  },
  subtitle: {
    fontSize: 14,
    fontFamily: "Inter_400Regular",
    color: "#6B7280",
    marginBottom: 16,
  },
  weekBanner: {
    backgroundColor: "#F5F3FF",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "#E9E3FB",
    padding: 14,
    marginBottom: 16,
  },
  weekBannerLabel: {
    fontSize: 11,
    letterSpacing: 0.8,
    fontFamily: "Inter_600SemiBold",
    color: "#8B7FB0",
    marginBottom: 3,
  },
  weekBannerValue: {
    fontSize: 17,
    fontFamily: "Outfit_700Bold",
    color: "#7C3AED",
  },
  weekBannerWarn: {
    fontSize: 13,
    fontFamily: "Inter_500Medium",
    color: "#B45309",
    lineHeight: 19,
    marginTop: 8,
  },
  weekBannerOk: {
    fontSize: 13,
    fontFamily: "Inter_500Medium",
    color: "#059669",
    marginTop: 8,
  },

  // ── Busy blocks ──
  blocksWrap: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 12,
  },
  blockPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: "#F5F3FF",
    borderWidth: 1,
    borderColor: "#E9E3FB",
    borderRadius: 12,
    paddingVertical: 9,
    paddingHorizontal: 12,
  },
  blockPillText: {
    fontSize: 14,
    fontFamily: "Inter_600SemiBold",
    color: "#5B21B6",
  },
  blockRemoveBtn: {
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: "#DDD6FE",
    alignItems: "center",
    justifyContent: "center",
  },
  blockRemoveText: {
    fontSize: 11,
    lineHeight: 13,
    fontFamily: "Inter_600SemiBold",
    color: "#5B21B6",
  },
  noBlocks: {
    fontSize: 13,
    fontFamily: "Inter_400Regular",
    color: "#9CA3AF",
    marginBottom: 12,
  },
  addBlockBtn: {
    alignSelf: "flex-start",
    backgroundColor: "#F3F4F6",
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 14,
    marginBottom: 14,
  },
  addBlockBtnText: {
    fontSize: 14,
    fontFamily: "Inter_600SemiBold",
    color: "#7C3AED",
  },
  freeRow: {
    backgroundColor: "#F9FAFB",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#F0F0F2",
    padding: 12,
  },
  freeLabel: {
    fontSize: 12,
    fontFamily: "Inter_600SemiBold",
    color: "#9CA3AF",
    marginBottom: 4,
  },
  freeValue: {
    fontSize: 14,
    fontFamily: "Inter_600SemiBold",
    color: "#111827",
    lineHeight: 20,
  },

  // ── Add-block modal ──
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(17,24,39,0.45)",
    justifyContent: "flex-end",
  },
  modalCard: {
    backgroundColor: "#FFFFFF",
    borderTopLeftRadius: 26,
    borderTopRightRadius: 26,
    paddingHorizontal: 22,
    paddingTop: 16,
    paddingBottom: 30,
  },
  modalHandle: {
    alignSelf: "center",
    width: 40,
    height: 5,
    borderRadius: 3,
    backgroundColor: "#E5E7EB",
    marginBottom: 16,
  },
  modalTitle: {
    fontSize: 19,
    fontFamily: "Outfit_700Bold",
    color: "#111827",
    marginBottom: 4,
  },
  modalSubtitle: {
    fontSize: 14,
    fontFamily: "Inter_400Regular",
    color: "#6B7280",
    marginBottom: 16,
  },
  pickerLabel: {
    fontSize: 12,
    letterSpacing: 0.6,
    fontFamily: "Inter_600SemiBold",
    color: "#9CA3AF",
    marginBottom: 8,
    marginTop: 6,
  },
  pickerScroll: {
    gap: 8,
    paddingRight: 8,
  },
  pickerChip: {
    minWidth: 60,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#E5E7EB",
    backgroundColor: "#F9FAFB",
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 12,
  },
  pickerChipActive: {
    backgroundColor: "#7C3AED",
    borderColor: "#7C3AED",
  },
  pickerChipDisabled: {
    opacity: 0.35,
  },
  pickerChipText: {
    fontSize: 13,
    fontFamily: "Inter_600SemiBold",
    color: "#374151",
  },
  pickerChipTextActive: {
    color: "#FFFFFF",
  },
  modalError: {
    fontSize: 13,
    fontFamily: "Inter_500Medium",
    color: "#B45309",
    marginTop: 12,
  },
  modalBtns: {
    flexDirection: "row",
    gap: 12,
    marginTop: 20,
  },
  modalBtn: {
    flex: 1,
    height: 50,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
  },
  modalBtnCancel: { backgroundColor: "#F3F4F6" },
  modalBtnCancelText: {
    fontSize: 15,
    fontFamily: "Inter_600SemiBold",
    color: "#6B7280",
  },
  modalBtnConfirm: { backgroundColor: "#7C3AED" },
  modalBtnConfirmText: {
    fontSize: 15,
    fontFamily: "Inter_600SemiBold",
    color: "#FFFFFF",
  },
  modalBtnDisabled: { opacity: 0.4 },
  dayCard: {
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#F3F4F6",
    borderRadius: 18,
    padding: 16,
    marginBottom: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 2,
  },
  dayTitle: {
    fontSize: 17,
    fontFamily: "PlusJakartaSans_600SemiBold",
    color: "#111827",
    marginBottom: 14,
  },
  timeSlider: {
    paddingRight: 8,
    gap: 8,
  },
  chip: {
    minWidth: 62,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#E5E7EB",
    backgroundColor: "#F9FAFB",
    borderRadius: 12,
    paddingVertical: 11,
    paddingHorizontal: 14,
  },
  chipActive: {
    backgroundColor: "#7C3AED",
    borderColor: "#7C3AED",
    shadowColor: "#7C3AED",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.28,
    shadowRadius: 10,
    elevation: 4,
  },
  chipText: {
    fontSize: 13,
    fontFamily: "Inter_600SemiBold",
    color: "#374151",
  },
  chipTextActive: {
    color: "#FFFFFF",
  },
  offChip: {
    backgroundColor: "#FFF1F2",
    borderColor: "#FBCFE8",
  },
  offChipActive: {
    backgroundColor: "#FCE7F3",
    borderColor: "#EC4899",
  },
  offChipText: {
    color: "#BE185D",
  },
  offChipTextActive: {
    color: "#9D174D",
  },
  summaryRow: {
    flexDirection: "row",
    gap: 10,
    marginTop: 14,
  },
  summaryBox: {
    flex: 1,
    backgroundColor: "#F9FAFB",
    borderRadius: 14,
    paddingVertical: 12,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: "#F3F4F6",
  },
  summaryLabel: {
    fontSize: 12,
    fontFamily: "Inter_600SemiBold",
    color: "#9CA3AF",
    marginBottom: 4,
  },
  summaryValue: {
    fontSize: 14,
    fontFamily: "Inter_600SemiBold",
    color: "#111827",
    lineHeight: 20,
  },
  weeklySummaryCard: {
    backgroundColor: "#FAFAFA",
    borderRadius: 18,
    padding: 16,
    borderWidth: 1,
    borderColor: "#F3F4F6",
    marginTop: 4,
  },
  weeklySummaryTitle: {
    fontSize: 14,
    fontFamily: "Inter_600SemiBold",
    color: "#111827",
    marginBottom: 12,
  },
  weeklySummaryRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    marginBottom: 8,
  },
  weeklySummaryDay: {
    width: 48,
    fontSize: 13,
    fontFamily: "Inter_600SemiBold",
    color: "#7C3AED",
  },
  weeklySummaryText: {
    flex: 1,
    fontSize: 13,
    fontFamily: "Inter_500Medium",
    color: "#374151",
    lineHeight: 19,
  },
  saveButton: {
    marginTop: 16,
    marginBottom: 24,
  },
  recapRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  recapDay: {
    width: 48,
    fontSize: 13,
    fontFamily: "Inter_600SemiBold",
    color: "#7C3AED",
  },
  recapValue: {
    flex: 1,
    textAlign: "right",
    fontSize: 14,
    fontFamily: "Inter_600SemiBold",
    color: "#111827",
  },
  recapValueOff: {
    color: "#9CA3AF",
    fontFamily: "Inter_500Medium",
  },
});
